### ISSUE TITLE
Make create-release.yml workflow working

### ISSUE THREAD

**Issue by kkokosa** [kkokosa/Strings.Abbreviations#7]
Unfortunately the mentioned workflow for creating releases after a new tag has been pushed is not working - even [Publish Nuget workflow](../tree/master/.github/workflows/publish-nuget.yml) does push a new tag:

```
creating new tag v0.1.3
executing: [git tag v0.1.3]
executing: [git push origin v0.1.3]
To https://github.com/kkokosa/Strings.Abbreviations
 * [new tag]         v0.1.3 -> v0.1.3
```

Although, it works if `git tag v...` and `git push origin v...` is made manually from command line.

**Comment by aochmann** [comment]
Hi @kkokosa I was looking into issue that workflow is not triggering after pushing new tag from another workflow.
In general it's related with `actions/checkout@v2` and `GITHUB_TOKEN `.

More details on here:
 * https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
 * https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/4

The workaround would be as described here:
 * https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
 * https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/8
 * or using `actions/checkout@v1` like here https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/5

Will let you later know if it works after I check on some example.
